/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Filipe
 */
public class Clientes_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Clientes_GUI
     */
    public Clientes_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        prod_BTN2 = new org.edisoncor.gui.button.ButtonIcon();
        prod_BTN3 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel2 = new javax.swing.JLabel();
        prod_BTN4 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel4 = new javax.swing.JLabel();
        prod_BTN5 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prod_BTN6 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel13 = new javax.swing.JLabel();
        codigo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        valor_unit_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        total_txt1 = new org.edisoncor.gui.textField.TextFieldRound();
        enviar_BTN = new org.edisoncor.gui.button.ButtonRound();
        atualizar_BTN = new org.edisoncor.gui.button.ButtonRound();
        deletar_BTN = new org.edisoncor.gui.button.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo menu.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        panelRect1.setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo mercado.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        panelRect1.add(panelImage2);
        panelImage2.setBounds(0, 0, 260, 170);

        prod_BTN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desfazer.png"))); // NOI18N
        prod_BTN2.setText("buttonIcon1");
        prod_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN2ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN2);
        prod_BTN2.setBounds(1110, 50, 130, 60);

        prod_BTN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/produtos.png"))); // NOI18N
        prod_BTN3.setText("buttonIcon1");
        prod_BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN3ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN3);
        prod_BTN3.setBounds(310, 50, 130, 60);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajuda");
        panelRect1.add(jLabel2);
        jLabel2.setBounds(670, 110, 60, 30);

        prod_BTN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clientes.png"))); // NOI18N
        prod_BTN4.setText("buttonIcon1");
        prod_BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN4ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN4);
        prod_BTN4.setBounds(470, 50, 130, 60);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clientes");
        panelRect1.add(jLabel4);
        jLabel4.setBounds(500, 120, 70, 14);

        prod_BTN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ponto-de-interrogacao.png"))); // NOI18N
        prod_BTN5.setText("buttonIcon1");
        panelRect1.add(prod_BTN5);
        prod_BTN5.setBounds(630, 50, 130, 60);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ajuda");
        panelRect1.add(jLabel5);
        jLabel5.setBounds(670, 110, 60, 30);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Voltar");
        panelRect1.add(jLabel6);
        jLabel6.setBounds(1150, 120, 60, 20);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Produtos");
        panelRect1.add(jLabel7);
        jLabel7.setBounds(340, 120, 70, 14);

        prod_BTN6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        prod_BTN6.setText("buttonIcon1");
        prod_BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN6ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN6);
        prod_BTN6.setBounds(1270, 50, 130, 60);

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sair");
        panelRect1.add(jLabel13);
        jLabel13.setBounds(1320, 120, 40, 20);

        panelImage1.add(panelRect1);
        panelRect1.setBounds(-10, -10, 1420, 160);
        panelImage1.add(codigo_txt);
        codigo_txt.setBounds(30, 400, 200, 40);

        valor_unit_txt.setToolTipText("R$ 0,00");
        valor_unit_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valor_unit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_unit_txtActionPerformed(evt);
            }
        });
        panelImage1.add(valor_unit_txt);
        valor_unit_txt.setBounds(30, 260, 200, 50);

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("              Nome:");
        jLabel10.setOpaque(true);
        panelImage1.add(jLabel10);
        jLabel10.setBounds(30, 210, 200, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Contato", "CPF"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(690, 150, 680, 500);

        jLabel8.setBackground(new java.awt.Color(0, 255, 255));
        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("              CPF:");
        jLabel8.setOpaque(true);
        panelImage1.add(jLabel8);
        jLabel8.setBounds(30, 350, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 102));
        panelImage1.add(jLabel1);
        jLabel1.setBounds(320, 170, 180, 0);

        jLabel9.setBackground(new java.awt.Color(0, 255, 255));
        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("              Código:");
        jLabel9.setOpaque(true);
        panelImage1.add(jLabel9);
        jLabel9.setBounds(30, 350, 200, 30);

        jLabel12.setBackground(new java.awt.Color(0, 255, 255));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("            Contato:");
        jLabel12.setOpaque(true);
        panelImage1.add(jLabel12);
        jLabel12.setBounds(280, 210, 200, 30);

        total_txt1.setToolTipText("R$ 0,00");
        total_txt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        total_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_txt1ActionPerformed(evt);
            }
        });
        panelImage1.add(total_txt1);
        total_txt1.setBounds(280, 260, 200, 50);

        enviar_BTN.setBackground(new java.awt.Color(255, 0, 0));
        enviar_BTN.setText("Enviar");
        panelImage1.add(enviar_BTN);
        enviar_BTN.setBounds(60, 500, 140, 40);

        atualizar_BTN.setBackground(new java.awt.Color(255, 0, 0));
        atualizar_BTN.setText("Atualizar");
        panelImage1.add(atualizar_BTN);
        atualizar_BTN.setBounds(290, 500, 140, 40);

        deletar_BTN.setBackground(new java.awt.Color(255, 0, 0));
        deletar_BTN.setText("Deletar");
        panelImage1.add(deletar_BTN);
        deletar_BTN.setBounds(180, 580, 140, 40);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 1400, 770);

        setSize(new java.awt.Dimension(1397, 772));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prod_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_prod_BTN2ActionPerformed

    private void prod_BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN3ActionPerformed
        // TODO add your handling code here:
        new Produtos_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prod_BTN3ActionPerformed

    private void prod_BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Clientes_GUI().setVisible(true);
    }//GEN-LAST:event_prod_BTN4ActionPerformed

    private void prod_BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prod_BTN6ActionPerformed

    private void valor_unit_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_unit_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_unit_txtActionPerformed

    private void total_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound atualizar_BTN;
    private org.edisoncor.gui.textField.TextFieldRound codigo_txt;
    private org.edisoncor.gui.button.ButtonRound deletar_BTN;
    private org.edisoncor.gui.button.ButtonRound enviar_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN2;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN3;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN4;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN5;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN6;
    private org.edisoncor.gui.textField.TextFieldRound total_txt1;
    private org.edisoncor.gui.textField.TextFieldRound valor_unit_txt;
    // End of variables declaration//GEN-END:variables
}
