/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Filipe
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("supermarket?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        pedidoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Pedido p");
        pedidoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pedidoQuery.getResultList();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        prod_BTN2 = new org.edisoncor.gui.button.ButtonIcon();
        prod_BTN3 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel2 = new javax.swing.JLabel();
        prod_BTN5 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buscar_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        code_txt = new org.edisoncor.gui.textField.TextFieldRound();
        unit_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();
        jLabel1 = new javax.swing.JLabel();
        caixa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel11 = new javax.swing.JLabel();
        subtotal_txt1 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonSeven3 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven4 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven5 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven7 = new org.edisoncor.gui.button.ButtonSeven();
        excluido_BTN = new org.edisoncor.gui.button.ButtonRound();
        nitem_txt = new org.edisoncor.gui.textField.TextFieldRound();
        editar_BTN = new org.edisoncor.gui.button.ButtonRound();
        inserir_BTN1 = new org.edisoncor.gui.button.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo menu.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        panelRect1.setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo mercado.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        panelRect1.add(panelImage2);
        panelImage2.setBounds(0, 0, 260, 170);

        prod_BTN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        prod_BTN2.setText("buttonIcon1");
        prod_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN2ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN2);
        prod_BTN2.setBounds(1230, 60, 130, 60);

        prod_BTN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/produtos.png"))); // NOI18N
        prod_BTN3.setText("buttonIcon1");
        prod_BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_BTN3ActionPerformed(evt);
            }
        });
        panelRect1.add(prod_BTN3);
        prod_BTN3.setBounds(310, 50, 130, 60);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajuda");
        panelRect1.add(jLabel2);
        jLabel2.setBounds(510, 110, 60, 30);

        prod_BTN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ponto-de-interrogacao.png"))); // NOI18N
        prod_BTN5.setText("buttonIcon1");
        panelRect1.add(prod_BTN5);
        prod_BTN5.setBounds(470, 50, 130, 60);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sair");
        panelRect1.add(jLabel6);
        jLabel6.setBounds(1280, 120, 40, 20);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Produtos");
        panelRect1.add(jLabel7);
        jLabel7.setBounds(340, 120, 70, 14);

        panelImage1.add(panelRect1);
        panelRect1.setBounds(-10, -10, 1420, 160);

        buscar_BTN.setBackground(new java.awt.Color(255, 0, 0));
        buscar_BTN.setText("Buscar");
        buscar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(buscar_BTN);
        buscar_BTN.setBounds(290, 500, 190, 40);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Caixa:");
        jLabel3.setOpaque(true);
        panelImage1.add(jLabel3);
        jLabel3.setBounds(50, 170, 110, 50);
        panelImage1.add(code_txt);
        code_txt.setBounds(30, 500, 200, 40);

        unit_txt.setToolTipText("R$ 0,00");
        unit_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        unit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_txtActionPerformed(evt);
            }
        });
        panelImage1.add(unit_txt);
        unit_txt.setBounds(30, 380, 200, 50);

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("            Unidade:");
        jLabel10.setOpaque(true);
        panelImage1.add(jLabel10);
        jLabel10.setBounds(30, 340, 200, 30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pedidoList, tabelaItens);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nitem}"));
        columnBinding.setColumnName("N°Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit}"));
        columnBinding.setColumnName("Unit");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codebar}"));
        columnBinding.setColumnName("Codigo de Barra");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${caixa}"));
        columnBinding.setColumnName("Caixa");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabelaItens);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(690, 150, 680, 360);

        jLabel8.setBackground(new java.awt.Color(0, 255, 255));
        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("         Codigo de Barra:");
        jLabel8.setOpaque(true);
        panelImage1.add(jLabel8);
        jLabel8.setBounds(30, 460, 200, 30);

        buttonSeven1.setBackground(new java.awt.Color(204, 0, 0));
        buttonSeven1.setText("Fechado");
        buttonSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven1ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven1);
        buttonSeven1.setBounds(190, 240, 116, 35);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 102));
        panelImage1.add(jLabel1);
        jLabel1.setBounds(320, 170, 180, 0);

        caixa_txt.setToolTipText("R$ 0,00");
        caixa_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        caixa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_txtActionPerformed(evt);
            }
        });
        panelImage1.add(caixa_txt);
        caixa_txt.setBounds(190, 170, 110, 50);

        jLabel11.setBackground(new java.awt.Color(0, 255, 255));
        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("        Numero do Pedido:");
        jLabel11.setOpaque(true);
        panelImage1.add(jLabel11);
        jLabel11.setBounds(280, 340, 200, 30);

        subtotal_txt1.setToolTipText("R$ 0,00");
        subtotal_txt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subtotal_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal_txt1ActionPerformed(evt);
            }
        });
        panelImage1.add(subtotal_txt1);
        subtotal_txt1.setBounds(750, 570, 540, 70);

        jLabel12.setBackground(new java.awt.Color(0, 255, 255));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("   Forma De Pagamento:");
        jLabel12.setOpaque(true);
        panelImage1.add(jLabel12);
        jLabel12.setBounds(30, 620, 370, 30);

        jLabel14.setBackground(new java.awt.Color(0, 255, 255));
        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("                                             SubTotal:");
        jLabel14.setOpaque(true);
        panelImage1.add(jLabel14);
        jLabel14.setBounds(690, 530, 670, 30);

        buttonSeven3.setBackground(new java.awt.Color(0, 255, 0));
        buttonSeven3.setText("Aberto");
        buttonSeven3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven3ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven3);
        buttonSeven3.setBounds(50, 240, 116, 35);

        buttonSeven4.setBackground(new java.awt.Color(0, 255, 255));
        buttonSeven4.setText("Pix");
        buttonSeven4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven4ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven4);
        buttonSeven4.setBounds(30, 660, 110, 35);

        buttonSeven5.setBackground(new java.awt.Color(0, 255, 255));
        buttonSeven5.setText("Dinheiro");
        buttonSeven5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven5ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven5);
        buttonSeven5.setBounds(280, 660, 116, 35);

        buttonSeven7.setBackground(new java.awt.Color(0, 255, 255));
        buttonSeven7.setText("Cartão");
        buttonSeven7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven7ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven7);
        buttonSeven7.setBounds(150, 660, 116, 35);

        excluido_BTN.setBackground(new java.awt.Color(255, 0, 0));
        excluido_BTN.setText("Excluir");
        excluido_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluido_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(excluido_BTN);
        excluido_BTN.setBounds(30, 550, 200, 40);

        nitem_txt.setToolTipText("R$ 0,00");
        nitem_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nitem_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitem_txtActionPerformed(evt);
            }
        });
        panelImage1.add(nitem_txt);
        nitem_txt.setBounds(280, 380, 200, 50);

        editar_BTN.setBackground(new java.awt.Color(255, 0, 0));
        editar_BTN.setText("Editar");
        editar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(editar_BTN);
        editar_BTN.setBounds(290, 450, 190, 40);

        inserir_BTN1.setBackground(new java.awt.Color(255, 0, 0));
        inserir_BTN1.setText("Inserir");
        inserir_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_BTN1ActionPerformed(evt);
            }
        });
        panelImage1.add(inserir_BTN1);
        inserir_BTN1.setBounds(290, 550, 190, 40);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 10, 1400, 770);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1397, 777));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unit_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unit_txtActionPerformed

    private void caixa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_txtActionPerformed

    }//GEN-LAST:event_caixa_txtActionPerformed

    private void subtotal_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotal_txt1ActionPerformed

    private void prod_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN2ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_prod_BTN2ActionPerformed

    private void prod_BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_BTN3ActionPerformed
        // TODO add your handling code here:
         new Produtos_GUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_prod_BTN3ActionPerformed

    private void buscar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_BTNActionPerformed
        Controller.Pedido_DAO.buscar();
    }//GEN-LAST:event_buscar_BTNActionPerformed

    private void excluido_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluido_BTNActionPerformed
     Controller.Pedido_DAO.excluir();
    }//GEN-LAST:event_excluido_BTNActionPerformed

    private void nitem_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitem_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitem_txtActionPerformed

    private void editar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_BTNActionPerformed
      Controller.Pedido_DAO.editar();
    }//GEN-LAST:event_editar_BTNActionPerformed

    private void inserir_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_BTN1ActionPerformed
      Controller.Pedido_DAO.inserir();
      Controller.Pedido_DAO.atualizarTabelaItens();
    }//GEN-LAST:event_inserir_BTN1ActionPerformed

    private void buttonSeven3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven3ActionPerformed
       
    }//GEN-LAST:event_buttonSeven3ActionPerformed

    private void buttonSeven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven1ActionPerformed
       caixa_txt.setText("");
    }//GEN-LAST:event_buttonSeven1ActionPerformed

    private void buttonSeven4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven4ActionPerformed
       
        new Dadosdoclient().setVisible(true);
    }//GEN-LAST:event_buttonSeven4ActionPerformed

    private void buttonSeven7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven7ActionPerformed
    new Dadosdoclient().setVisible(true);
    }//GEN-LAST:event_buttonSeven7ActionPerformed

    private void buttonSeven5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven5ActionPerformed
    new Dadosdoclient().setVisible(true);
    }//GEN-LAST:event_buttonSeven5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.button.ButtonRound buscar_BTN;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven3;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven4;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven5;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven7;
    public static org.edisoncor.gui.textField.TextFieldRound caixa_txt;
    public static org.edisoncor.gui.textField.TextFieldRound code_txt;
    public static org.edisoncor.gui.button.ButtonRound editar_BTN;
    private javax.persistence.EntityManager entityManager;
    public static org.edisoncor.gui.button.ButtonRound excluido_BTN;
    public static org.edisoncor.gui.button.ButtonRound inserir_BTN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static org.edisoncor.gui.textField.TextFieldRound nitem_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private java.util.List<View.Pedido> pedidoList;
    private javax.persistence.Query pedidoQuery;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN2;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN3;
    private org.edisoncor.gui.button.ButtonIcon prod_BTN5;
    public static org.edisoncor.gui.textField.TextFieldRound subtotal_txt1;
    public static javax.swing.JTable tabelaItens;
    public static org.edisoncor.gui.textField.TextFieldRound unit_txt;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
